name: flutter_chat_app
description: One-to-one chat and Firebase auth

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  google_sign_in: ^6.1.5
  firebase_analytics: ^10.8.0
  firebase_auth: ^4.20.0
  firebase_database: ^10.4.5
  firebase_storage: ^11.6.6
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true